---
- hosts: myWebServers
  become: yes
  tasks:
  - name: install java on ubantu
    apt: 
     name: openjdk-8-jre
     state: present
    when: ansible_os_family =="Debian"
  - name: install java o RedHat
    yum:
     name: java-1.8.0-openjdk
     state: present
    when: ansible_os_family =="RedHat"    