---
- hosts: 172.31.34.106
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: copy file into ansible node side
    copy:
       src: staticfile.txt
       dest: /home/ubuntu/mystaticfile.txt    