---
- hosts: 172.31.34.106
  become: yes
  tasks:
  - name:
    apt:
      name: git
      state: present

  - name: install tree
    apt:
     name: tree
     state: present

  - name: install wgit
    apt:
     name: wgit
     state: present      