---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver on ubantu ansibal node
    apt: 
     name: apache2
     state: present
  - name: i want to start webserver on ubantu ansibal nodes
    service:
      name: apache2
      state: restarted 
